name: prognostics_new_run
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # container: docker://dvcorg/cml:latest
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      
      
      - name: Setup R
        uses: r-lib/actions/setup-r@master
      - name: Configure java
        run: sudo R CMD javareconf
      - name: Install curl
        run: sudo apt-get install libcurl4-openssl-dev
        
      - name: Setup dependencies
        run: |
          R -e 'install.packages("renv")' 
          R -e 'renv::restore()'
          
      - name: main
        env: 
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          R -e 'renv::run("main_prognostics.R")'
          
          # Add model diagnostics plot to report
          echo "Model diagnostics" > report.md
          cml-publish mdl_diagnostics.png --md >> report.md 
          
          # Add model predictions plot to report
          echo "Model predictions" >> report.md
          cml-publish mdl_predictions.png --md >> report.md
          
          # Send report
          cml-send-comment report.md
